FROM node:18-alpine

# Instalar clientes de bases de datos y dependencias necesarias
RUN apk add --no-cache \
    postgresql-client \
    mongodb-tools \
    openssl

WORKDIR /app

# Crear directorio scripts
RUN mkdir -p /app/scripts

# No copiamos archivos para aprovechar el volumen montado

# Exponer puerto de desarrollo
EXPOSE 3000

# Comando para iniciar la aplicación en modo desarrollo
CMD ["npm", "run", "dev"] 